version: 2
jobs:
  build:
    working_directory: ~/ProjetSEGApp
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "SEGApp/build.gradle" }}-{{ checksum  "SEGApp/app/build.gradle" }}
      - run:
         name: Chmod permissions  
         command: sudo chmod +x ./SEGApp/gradlew
      - run:
          name: Download Dependencies
          command: ./SEGApp/gradlew SEGApp/androidDependencies
      - save_cache:
          paths:
            - ~/SEGApp/.gradle
          key: jars-{{ checksum "SEGApp/build.gradle" }}-{{ checksum  "SEGApp/app/build.gradle" }}
      - run:
          name: Run UnitTest
          command: ./SEGApp/gradlew SEGApp/test
      - store_artifacts:
          path: SEGApp/app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: SEGApp/app/build/test-results
 